/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <BIT_MATH.h>
#include "ERROR_TYPE.h"
#include "STM32F303xx.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"

int main(void)
{
	uint8_t x ;
	uint8_t
	RCC_voidSetClockStatus(RCC_CLK_HSI, RCC_CLK_ON);
	RCC_voidSetSystemClock(RCC_CLK_HSI);
	RCC_voidEnable_AHB_clock(RCC_AHB_IOPAEN);

	for(;;)
	{
		display_num();
	};
}

void display_num()
{
	GPIO_pinConfig_t A = {.portId = GPIO_PORTC,.pinId = GPIO_PIN10,.pinMode = GPIO_OUTPUT,.pinOutputType = GPIO_PUSH_PULL};
	GPIO_pinConfig_t B = {.portId = GPIO_PORTC,.pinId = GPIO_PIN12,.pinMode = GPIO_OUTPUT,.pinOutputType = GPIO_PUSH_PULL};
	GPIO_pinConfig_t C = {.portId = GPIO_PORTF,.pinId = GPIO_PIN6,.pinMode = GPIO_OUTPUT,.pinOutputType = GPIO_PUSH_PULL};
	GPIO_pinConfig_t D = {.portId = GPIO_PORTF,.pinId = GPIO_PIN7,.pinMode = GPIO_OUTPUT,.pinOutputType = GPIO_PUSH_PULL};
	GPIO_pinConfig_t E = {.portId = GPIO_PORTA,.pinId = GPIO_PIN13,.pinMode = GPIO_OUTPUT,.pinOutputType = GPIO_PUSH_PULL};
	GPIO_pinConfig_t F = {.portId = GPIO_PORTA,.pinId = GPIO_PIN14,.pinMode = GPIO_OUTPUT,.pinOutputType = GPIO_PUSH_PULL};
	GPIO_pinConfig_t G = {.portId = GPIO_PORTA,.pinId = GPIO_PIN15,.pinMode = GPIO_OUTPUT,.pinOutputType = GPIO_PUSH_PULL};

	GPIO_u8InitPin(&A);
	GPIO_u8InitPin(&B);
	GPIO_u8InitPin(&C);
	GPIO_u8InitPin(&D);
	GPIO_u8InitPin(&E);
	GPIO_u8InitPin(&F);
	GPIO_u8InitPin(&G);

	// print (5)

	GPIO_u8SetPinValue(GPIO_PORTB, GPIO_PIN0, GPIO_PIN_HIGH); //A
	GPIO_u8SetPinValue(GPIO_PORTB, GPIO_PIN1, GPIO_PIN_LOW);  //B
	GPIO_u8SetPinValue(GPIO_PORTB, GPIO_PIN2, GPIO_PIN_HIGH); //C
	GPIO_u8SetPinValue(GPIO_PORTB, GPIO_PIN3, GPIO_PIN_HIGH); //D
	GPIO_u8SetPinValue(GPIO_PORTB, GPIO_PIN4, GPIO_PIN_LOW);  //E
	GPIO_u8SetPinValue(GPIO_PORTB, GPIO_PIN5, GPIO_PIN_HIGH); //F
	GPIO_u8SetPinValue(GPIO_PORTB, GPIO_PIN6, GPIO_PIN_HIGH); //G



}







//GPIOC->ODR=n;







//	GPIO_u8SetPinValue(GPIO_PORTC, GPIO_PIN0, GPIO_PIN_HIGH);
//	GPIO_u8SetPinValue(GPIO_PORTC, GPIO_PIN1, GPIO_PIN_HIGH);
//	GPIO_u8SetPinValue(GPIO_PORTC, GPIO_PIN2, GPIO_PIN_HIGH);
//	GPIO_u8SetPinValue(GPIO_PORTC, GPIO_PIN3, GPIO_PIN_HIGH);
//	GPIO_u8SetPinValue(GPIO_PORTC, GPIO_PIN4, GPIO_PIN_HIGH);
//	GPIO_u8SetPinValue(GPIO_PORTC, GPIO_PIN5, GPIO_PIN_HIGH);
//	GPIO_u8SetPinValue(GPIO_PORTC, GPIO_PIN6, GPIO_PIN_HIGH);
//	GPIO_u8SetPinValue(GPIO_PORTC, GPIO_PIN7, GPIO_PIN_HIGH);
